# A Framework for Leveraging LLMs for Scene Analysis and Cognitive Processing

## Setup

In [1]:
import os
HOME = os.getcwd()

os.chdir(HOME)
print(HOME)

d:\home\Documents\Github\human_patterns_exploration

In [5]:
import pandas as pd

from src.processor.DataProcessor import DataProcessor

In [6]:

DATA_DIR = os.path.join(HOME, "data", "experiments")
IMAGE_DIR = os.path.join(HOME, "data", "images")
RESULTS_DIR = os.path.join(HOME, "outputs")

SAM_CONFIG = os.path.join("configs", "sam2.1", "sam2.1_hiera_l.yaml")
SAM_MODEL =  os.path.join(HOME, "checkpoints", "sam2.1_hiera_large.pt")

print("HOME:", HOME)
print("DATA_DIR:", DATA_DIR)
print("IMAGE_DIR:", IMAGE_DIR)
print("SAM_CONFIG:", SAM_CONFIG)
print("SAM_MODEL:", SAM_MODEL)

HOME: d:\home\Documents\Github\human_patterns_exploration
DATA_DIR: d:\home\Documents\Github\human_patterns_exploration\data\experiments
IMAGE_DIR: d:\home\Documents\Github\human_patterns_exploration\data\images
SAM_CONFIG: configs\sam2.1\sam2.1_hiera_l.yaml
SAM_MODEL: d:\home\Documents\Github\human_patterns_exploration\checkpoints\sam2.1_hiera_large.pt

In [9]:
processor = DataProcessor( path="./data/experiments/XSQ_Expt1_Data_2.csv", condition=1, group=1 )
exp_data = processor.process_participant_data()
exp_data

,ParticipantID,Group,Condition,ItemNum,X,Y,FixationDuration,Rel_Scene_Region_Rel_X1,Rel_Scene_Region_Rel_Y1,Rel_Scene_Region_Rel_X2,...,Irrev_Scene_Region_X1,Irrev_Scene_Region_Y1,Irrev_Scene_Region_X2,Irrev_Scene_Region_Y2,Irrev_Scene_Region_IrrelSceneFix,Cntl_Scene_Region_X1,Cntl_Scene_Region_Y1,Cntl_Scene_Region_X2,Cntl_Scene_Region_Y2,Cntl_Scene_Region_CntlSceneFix
0,2,1,1,1,398.0,314.2,291,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,0.0
1,2,1,1,1,323.4,398.2,421,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
2,2,1,1,1,23.6,492.2,268,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
3,2,1,1,1,483.6,565.0,162,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
4,2,1,1,2,379.6,305.1,206,0.0,435.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117229,104,1,1,121,689.9,186.5,230,0.0,248.0,800.0,...,0.0,0.0,800.0,247.0,1.0,0.0,380.0,800.0,680.0,0.0
117230,104,1,1,121,701.8,180.0,385,0.0,248.0,800.0,...,0.0,0.0,800.0,247.0,1.0,0.0,380.0,800.0,680.0,0.0
117231,104,1,1,121,549.4,241.7,178,0.0,248.0,800.0,...,0.0,0.0,800.0,247.0,1.0,0.0,380.0,800.0,680.0,0.0
117232,104,1,1,121,535.1,248.1,248,0.0,248.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,0.0
117233,104,1,1,121,547.9,185.7,328,0.0,248.0,800.0,...,0.0,0.0,800.0,247.0,1.0,0.0,380.0,800.0,680.0,0.0

## Participant Gaze

In [4]:
prompt_diameter = 10
prompt_n_points = 5

# colors for eye gaze plots
font_color =  "yellow"          
COLOR_CODE_1 = "fixation_scarletred_meddark"
COLOR_CODE_2 = "aluminium"
COLOR_CODE_3 = "yellow"

In [5]:
# load experiment data
data_path = os.path.join(DATA_DIR , "XSQ_Expt1_Data_2.csv")
data = pd.read_csv( data_path )
data.head()

,ParticipantID,Group,Condition,ItemNum,X,Y,FixationDuration,Rel_Scene_Region_Rel_X1,Rel_Scene_Region_Rel_Y1,Rel_Scene_Region_Rel_X2,...,Irrev_Scene_Region_X1,Irrev_Scene_Region_Y1,Irrev_Scene_Region_X2,Irrev_Scene_Region_Y2,Irrev_Scene_Region_IrrelSceneFix,Cntl_Scene_Region_X1,Cntl_Scene_Region_Y1,Cntl_Scene_Region_X2,Cntl_Scene_Region_Y2,Cntl_Scene_Region_CntlSceneFix
0,2,1,1,1,398.0,314.2,291,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,0.0
1,2,1,1,1,323.4,398.2,421,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
2,2,1,1,1,23.6,492.2,268,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
3,2,1,1,1,483.6,565.0,162,0.0,464.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,1.0
4,2,1,1,2,379.6,305.1,206,0.0,435.0,800.0,...,0.0,0.0,800.0,247.0,0.0,0.0,380.0,800.0,680.0,0.0

## Image Segmentation and Mask Generation

In [ ]:
CENTER_BIAS_SECONDS = 1    # remove first 1 second of data to remove center bias

prompt_types = ["point", "circle", "triangle", "cross"]

GENERATE_MASKS = True

if GENERATE_MASKS:      
    #for img_id in range(1, 2):
        img_id = 1
        for prompt_type in prompt_types:
            #image_data = segment_image(img_id, data, condition_id=1, center_bias_seconds=CENTER_BIAS_SECONDS, prompt_type=prompt_type,  img_type="exp")
            image_data = segment_image(img_id, data, condition_id=3, center_bias_seconds=CENTER_BIAS_SECONDS, prompt_type=prompt_type,  img_type="exp")

### Find the best mask for each participant

In [6]:
IMG_ID = 2
IMG_TYPE = "unexp"
PROMPT_TYPE = "point"

participant_ids = get_participant_ids( os.path.join(RESULTS_DIR, "masks_gaze_driven", PROMPT_TYPE) , IMG_TYPE) 
len(participant_ids)

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'd:\\home\\Documents\\Github\\human_patterns_exploration\\outputs\\masks_gaze_driven\\point'

In [7]:
P_INDX = 8
print(participant_ids[P_INDX])
img_data, participant_data = load_image_data(IMG_ID, IMG_TYPE, participant_id=participant_ids[P_INDX], prompt_type=PROMPT_TYPE)

img_data.draw_fixations( participant_data, fix_color=stl.COLORS[COLOR_CODE_1][0], fix_edge_color=stl.COLORS[COLOR_CODE_2][1], size = 25 )

NameError: name 'participant_ids' is not defined

In [8]:

# plot scan path
img_data.draw_scanpath( participant_data, fix_color=stl.COLORS[COLOR_CODE_1][0], fix_edge_color=stl.COLORS[COLOR_CODE_2][1], font_color=stl.COLORS[font_color][1], fontsize=14 )

NameError: name 'img_data' is not defined

- Generalized Linear Model. Exploitation / Exploration
- look at the patterns of each group within a trial to see if they switch between them.

In [9]:
get_mask_candidates(2, 6, prompt_types, "unexp")

Pickle file not found: d:\home\Documents\Github\human_patterns_exploration\outputs\masks_gaze_driven\point\IMG_2_unexp_Part_6.pkl

FileNotFoundError: [Errno 2] No such file or directory: 'd:\\home\\Documents\\Github\\human_patterns_exploration\\outputs\\masks_gaze_driven\\point\\IMG_2_unexp_Part_6.pkl'

In [10]:
find_best_mask(IMG_ID, participant_ids, prompt_types, "unexp")

NameError: name 'participant_ids' is not defined

In [102]:
participant_ids = [p for p in participant_ids if p != 11]
participant_ids = [p for p in participant_ids if p != 17]
participant_ids = [p for p in participant_ids if p != 24]
participant_ids = [p for p in participant_ids if p != 36]
participant_ids = [p for p in participant_ids if p != 41]
participant_ids = [p for p in participant_ids if p != 42]
participant_ids = [p for p in participant_ids if p != 46]
participant_ids = [p for p in participant_ids if p != 83]
participant_ids = [p for p in participant_ids if p != 89]
participant_ids = [p for p in participant_ids if p != 97]

In [103]:
def label_masks_openai(participant_ids, img_id, img_type, model="gpt-4o", filename = "best_labels", output_dir = os.path.join(RESULTS_DIR, "masks_gaze_driven", "best_mask_labeling") ):

    df = pd.DataFrame(columns=["participant_id", "image_id", "image_path", "mask_id", "mask_path", "xmin", "xmax", "ymin", "ymax", "prompt_type", "X", "Y", "label1", "label2", "label3", "label4", "label5", "label6", "label7", "label8", "label9", "label10", "best_label", "scene_desc"])

    row = 0
    for part_indx in range(len(participant_ids)):

        print(f"Processing participant {part_indx}/{len(participant_ids)}")
        print("indx", part_indx)
        participant_id = participant_ids[part_indx]
        print("participant_id", participant_id)

        try:

            img_scene_data, _ = load_image_data(img_id, img_type, participant_id=participant_id, prompt_type="point")
        except:
            print(f"Participant {participant_id} not found")
            continue

        image_path = img_scene_data.path

        scene_desc = open_ai_scene_description(img_scene_data, temperature=0.1)
        scene_desc = scene_desc.replace("*", "")

        res = load_best_masks(img_id, participant_id, IMG_TYPE)

        mask_keys = list(res.keys())
        labels = []
        for mask_key in mask_keys:
            mask_id = mask_key
            mask_path = res[mask_id].path
            xmin = res[mask_id].x_min
            xmax = res[mask_id].x_max
            ymin = res[mask_id].y_min
            ymax = res[mask_id].y_max
            prompt_type = res[mask_id].prompt_type
            prompt = res[mask_id].prompt[0]
            
            for i in range(1, 11):
                mask_label = open_ai_mask_labeling(res[mask_id], temperature=0.1)

                # if mask label is of type list, then append the first element to the labels list
                if isinstance(mask_label, list):
                    labels.append(mask_label[0].replace("- ", ""))
                else:
                    labels.append(mask_label.replace("- ", ""))
            
            print(labels)

            # get the most frequent label from the list
            best_label = most_frequent_label(labels)

            df.loc[row] = [participant_id, img_id, image_path, mask_id, mask_path, xmin, xmax, ymin, ymax, prompt_type, prompt[0],prompt[1],labels[0], labels[1], labels[2], labels[3], labels[4], labels[5], labels[6], labels[7], labels[8], labels[9], best_label, scene_desc]
            row += 1
            labels = []
    
    df.to_csv(os.path.join(output_dir, f"{filename}_{model}_{IMG_TYPE}.csv"), index=False)
    return df


from collections import Counter

def most_frequent_label(labels):
    if not labels:
        return None  # Return None if the list is empty
    
    label_counts = Counter(labels)
    most_common_label, _ = label_counts.most_common(1)[0]  # Get the most frequent label
    
    return most_common_label

In [101]:

IMG_ID = 2
IMG_TYPE = "unexp"
PROMPT_TYPE = "point"

participant_ids = get_participant_ids( os.path.join(RESULTS_DIR, "masks_gaze_driven", PROMPT_TYPE) , IMG_TYPE) 
len(participant_ids)

44

In [104]:
df =  label_masks_openai(participant_ids, IMG_ID, IMG_TYPE, model="gpt-4o", output_dir = os.path.join(RESULTS_DIR, "masks_gaze_driven", "best_mask_labeling") )

Processing participant 0/34
indx 0
participant_id 6
Main Scene Processed in: 7.160217046737671 sec

In [ ]:

IMG_ID = 1
IMG_TYPE = "unexp"
PROMPT_TYPE = "point"

participant_ids1 = get_participant_ids( os.path.join(RESULTS_DIR, "masks_gaze_driven", PROMPT_TYPE) , IMG_TYPE) 
len(participant_ids1)

In [ ]:
df1 =  label_masks_openai(participant_ids1, IMG_ID, IMG_TYPE, model="gpt-4o", output_dir = os.path.join(RESULTS_DIR, "masks_gaze_driven", "best_mask_labeling") )

In [ ]:

# Step 2: Label the mask based on the scene context
mask_prompt = f"""You previously analyzed the main scene and described it as follows:
{scene_desc}
Now, analyze the new image, which is a **subset** (masked portion) of the main scene.
Your task:
1. Identify the object(s) in the masked region.
2. Assign the most contextually appropriate label based on the previous scene analysis.
3. If uncertain, explain the possible interpretations based on the overall scene.

Respond with:
- **Detected Object:** [Object Name]
- **Scene Context:** [Why it is likely this object based on the full scene]
"""

start_time = time.time()
mask_resp, mask_label, mask_duration = llava.analyse_image(img_mask_data, mask_prompt, temperature=0.1)
print("Mask Processed in:", time.time() - start_time, "sec")

# Output results
print("Main Scene Description:\n", scene_desc)
print("\nMask Labeling:\n", mask_label)